### PR TITLE
Documentation update

### PR DESCRIPTION
**Pull request by j9t**
Added sum.cumo references

### CODE REVIEW

**Comment by j9t** [comment]
@svewag, @escapedcat, not sure how to deal with the circleci issue—could you check, is this to be expected after a Markdown file update?

**Comment by svewag** [comment]
Don‘t know 🤷‍♂️
@escapedcat ?

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by escapedcat** [comment]
The `.circleci`-config is missing in the feature branche.  
@j9t please update the feature branch with development and try again.

**Comment by j9t** [comment]
Done. There was a mismatch between development and master, from which I had pulled my branch.

@escapedcat, do you plan to merge the CircleCI updates into master?

@svewag, could you review the update?

(Thanks!)

**Pull request merged**
